FROM alpine:edge
MAINTAINER Leo <thinkabit.ukim@gmail.com>

RUN rm /etc/apk/repositories \
    && printf -- >> /etc/apk/repositories \
    'http://dl-cdn.alpinelinux.org/alpine/edge/%s\n' \
    main community testing \
    && printf -- >> /etc/apk/repositories \
    '/home/alpine/packages/%s\n' \
    main community testing

RUN apk add -U --no-cache alpine-sdk abuild sudo openssh-server shadow fish
RUN apk upgrade -a

RUN /usr/bin/ssh-keygen -A
RUN printf "Port %%PORT%%\nListenAddress localhost\nPermitEmptyPasswords yes\n" >> /etc/ssh/sshd_config

USER root

CMD ["/usr/sbin/sshd", "-D"]
