FROM alpine:edge
MAINTAINER Leo <thinkabit.ukim@gmail.com>

RUN rm /etc/apk/repositories \
    && printf -- >> /etc/apk/repositories \
    'http://dl-cdn.alpinelinux.org/alpine/edge/%s\n' \
    main community testing \
    && printf -- >> /etc/apk/repositories \
    '/home/alpine/packages/%s\n' \
    main community testing

RUN apk add -U --no-cache alpine-sdk abuild sudo openssh-server shadow fish
RUN apk upgrade -a

RUN /usr/bin/ssh-keygen -A
RUN printf "Port %%PORT%%\nListenAddress localhost\nPermitEmptyPasswords yes\n" >> /etc/ssh/sshd_config

RUN adduser -D -u %%UID%% -g %%GID%% -h /home/alpine -D alpine \
    && addgroup alpine abuild \
    && echo 'alpine ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers

RUN sed -i 's|alpine:!|alpine:*|' /etc/shadow

USER root

CMD ["/usr/sbin/sshd", "-D"]
