FROM alpine:edge
MAINTAINER Leo <thinkabit.ukim@gmail.com>

RUN rm /etc/apk/repositories \
    && printf -- >> /etc/apk/repositories \
    'http://dl-cdn.alpinelinux.org/alpine/edge/%s\n' \
    main community testing \
    && printf -- >> /etc/apk/repositories \
    '/home/alpine/packages/%s\n' \
    main community testing

RUN apk add -U --no-cache alpine-sdk abuild sudo openssh-server shadow
RUN apk upgrade -a

RUN /usr/bin/ssh-keygen -A
RUN printf "Port %%PORT%%\nListenAddress localhost\nPermitEmptyPasswords yes\n" >> /etc/ssh/sshd_config

RUN adduser -D -u %%UID%% -g %%GID%% -h /home/alpine -D alpine \
    && addgroup alpine abuild \
    && echo 'alpine ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers

USER alpine
WORKDIR /home/alpine
COPY alpine-dev-env.pub alpine-dev-env.pub

RUN date
RUN mkdir .ssh \
    && cat alpine-dev-env.pub >> .ssh/authorized_keys \
    && chmod og-wx .ssh/authorized_keys \
    && rm -f alpine-dev-env.pub

RUN mkdir packages

USER root

RUN sed -i 's|alpine:!|alpine:*|' /etc/shadow

CMD ["/usr/sbin/sshd", "-D"]
